[package]
name = "rusty-baduk"
version = "1.0.0"
authors = ["dmitri-mcguckin <dmitri.mcguckin26@gmail.com>", "dunlapc4 <conor4@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
